"""推薦ランキング（`PROJECT_SPEC.md` §13, §14, §15）。"""

from techradar.recommendation.composition import (
    ComposedFeed,
    CompositionStats,
    FeedSlot,
    SlotStats,
    compose_feed,
    compose_feed_with_stats,
)
from techradar.recommendation.config import (
    ScoringConfig,
    ScoringConfigError,
    get_scoring_config,
    load_scoring_config,
)
from techradar.recommendation.ranking import (
    AuthorityGate,
    CandidateSignature,
    FeedComposition,
    FreshnessSettings,
    InterestProfile,
    InterestSettings,
    MatchSettings,
    NoveltySettings,
    RankingLimits,
    ScoreBreakdown,
    ScoredCandidate,
    ScorePenalties,
    ScoreWeights,
    ScoringSettings,
    build_reason_summary,
    compute_freshness,
    compute_interest_similarity,
    compute_novelty,
    compute_source_article_match,
    cosine_similarity,
    rank_candidates,
    score_candidate,
)

__all__ = [
    "AuthorityGate",
    "CandidateSignature",
    "ComposedFeed",
    "CompositionStats",
    "FeedComposition",
    "FeedSlot",
    "FreshnessSettings",
    "InterestProfile",
    "InterestSettings",
    "MatchSettings",
    "NoveltySettings",
    "RankingLimits",
    "ScoreBreakdown",
    "ScorePenalties",
    "ScoreWeights",
    "ScoredCandidate",
    "ScoringConfig",
    "ScoringConfigError",
    "ScoringSettings",
    "SlotStats",
    "build_reason_summary",
    "compose_feed",
    "compose_feed_with_stats",
    "compute_freshness",
    "compute_interest_similarity",
    "compute_novelty",
    "compute_source_article_match",
    "cosine_similarity",
    "get_scoring_config",
    "load_scoring_config",
    "rank_candidates",
    "score_candidate",
]
