/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interest Articles
         * @description 関心記事一覧を返す（`PROJECT_SPEC.md` §6.3、検索・絞り込み・ページングは Issue #91）。
         *
         *     手動登録・Good・保存の3経路のみを対象にし、登録日時（`user_articles.created_at`）
         *     降順で返す。タイブレークに `user_articles.id` を使う。
         *
         *     ページングは番号付き（`page` / `limit`）で、`GET /api/feed` と同じく offset として
         *     扱う。範囲外の `page` はエラーにせず空の `items` を返す。Issue #91 以前は cursor
         *     方式だったが、目的のページへ直接移動できるようにするため置き換えた。
         */
        get: operations["list_interest_articles_api_articles_get"];
        put?: never;
        /**
         * Create Article Registration
         * @description URL を登録し、記事取得ジョブを積む。
         *
         *     同じ URL（正規化後）を何度も登録しても fetch ジョブを積み増さないよう、
         *     既存登録があればそれをそのまま返す。
         */
        post: operations["create_article_registration_api_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Import Article Registrations
         * @description URL リストファイルをアップロードし、行ごとに URL を抽出して一括登録する（Issue #39）。
         *
         *     1件でも不正な行があっても全体を拒否せず、抽出できた URL をファイル内の出現順に
         *     処理する。ファイルサイズ・抽出後の URL 件数が上限を超える場合は DB を一切
         *     変更せず 413 を返す（`_read_upload_within_limit` / 抽出後件数チェックのどちらも、
         *     行ごとの DB 処理を始める前に完了させることで担保する）。
         */
        post: operations["bulk_import_article_registrations_api_articles_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/registrations/{registration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article Registration
         * @description 登録の状態を取得する。
         *
         *     作成側と同じく `user_id` で絞る。絞らないままにすると、認証を導入した際に
         *     このエンドポイントだけ他ユーザーの登録を返してしまう。
         */
        get: operations["get_article_registration_api_articles_registrations__registration_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{article_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Article Feedback
         * @description 記事へ Good / Bad / 保存を記録する（`PROJECT_SPEC.md` §7）。
         *
         *     合わせてトピック単位の選好（`user_topic_preferences`）を同期更新し
         *     （`update_topic_preferences`）、関心クラスタの再構築ジョブを積む
         *     （`_enqueue_interest_cluster_rebuild`、Issue #15）。
         */
        post: operations["create_article_feedback_api_articles__article_id__feedback_post"];
        /**
         * Delete Article Feedback
         * @description 記事へのフィードバックを取り消す。
         *
         *     Good / 保存に由来する `user_articles` 行も合わせて削除する
         *     （手動登録由来の行は残す）。関心記事の構成が変わりうるため、関心クラスタの
         *     再構築ジョブも積む。
         *
         *     トピック単位の選好（`user_topic_preferences`）は、取り消し後の直近
         *     フィードバック集合から `negative_weight` を再計算する
         *     （`recompute_topic_preferences_after_removal`、Issue #15 自己レビュー 1）。
         *     `update_topic_preferences`（POST 側）が使う増加方向のみの更新関数は
         *     取り消しには使わない（「上がった分を差し引く」処理を持たないため）。
         *
         *     呼び出し順序が重要: `session.delete(feedback)` の後に
         *     `session.flush()` で DELETE を確定させてから
         *     `recompute_topic_preferences_after_removal` を呼ぶ。先に確定させないと、
         *     再計算が読む「直近フィードバック」に削除対象自身が残ったままになり、
         *     取り消したはずのフィードバックが再計算結果に混入してしまう
         *     （`recompute_topic_preferences_after_removal` の docstring 参照）。
         */
        delete: operations["delete_article_feedback_api_articles__article_id__feedback_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{article_id}/interest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Interest Article
         * @description 記事を関心記事一覧から除外する。
         *
         *     `user_articles` の該当行を削除するだけで、`article_feedback` には触れない
         *     （Bad フィードバックも付けない）。「興味がない」（Bad）と「間違って登録した」
         *     （一覧からの除外）は別の意思表示のため区別する（Issue #14 ヒアリング済み決定事項）。
         */
        delete: operations["delete_interest_article_api_articles__article_id__interest_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{article_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Article Recommendations
         * @description 指定記事に近い記事を推薦する（`PROJECT_SPEC.md` §13.1）。
         *
         *     構成比は適用せず、`rank_candidates` の上位をそのまま rank 昇順で返す
         *     （`recommendation/service.py` の ARTICLE_BASED モード）。
         */
        post: operations["create_article_recommendations_api_articles__article_id__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Crawl Run
         * @description 巡回ジョブを enqueue する。
         *
         *     UI のボタン連打などで重複起動されると、`crawl_sources` 1件ごとに発生する
         *     検索 API / LLM 呼び出しが無制限に積み上がり、追加課金ゼロという前提に
         *     直接影響する。pending または実行中 status の `crawl_sources` ジョブが既に
         *     存在する場合は新規作成せず、その job_id を 200 OK で返す。存在しなければ
         *     従来どおり新規に enqueue して 201 Created を返す。
         *
         *     事前確認と INSERT の間には別リクエストが割り込みうる（TOCTOU）。SELECT 時点で
         *     対象の行が無い以上、行ロックでは塞げないため、最終的な排他は部分ユニーク
         *     インデックス `ux_jobs_active_crawl_sources` に任せ、ここではその違反を
         *     「相手が先に積んだ」ものとして扱う。
         */
        post: operations["create_crawl_run_api_crawl_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feed
         * @description Discover フィードを返す（`PROJECT_SPEC.md` §13.2、検索・絞り込み・ページングは Issue #90）。
         *
         *     `q` / `topics` / `technologies` / `published_from` / `published_to` /
         *     `source_domain` / `max_age_days` はいずれも省略可能な絞り込み条件で、全候補を
         *     対象に推薦を作り直す（決定済みの設計、`generate_recommendations` の
         *     `feed_filters`）。条件を反映したフィンガープリントが一致する直近の DISCOVER
         *     run が再利用してよい時間内（`config/scoring.yaml` の
         *     `limits.feed_run_reuse_seconds`）ならその run を再利用し、そうでなければ
         *     新しい run を生成する（`_resolve_discover_run_id`）。
         *
         *     `max_age_days` はフィードの対象期間そのもの（候補の絞り込み）を変える
         *     パラメータで、freshness スコアの減衰基準（`ranking.compute_freshness`）とは
         *     無関係（Issue #90 自己レビュー、`FeedFilters.max_age_days` のコメント参照）。
         *     従来は `config/scoring.yaml` の `freshness.max_age_days`（既定 7 日）を
         *     超える公開日で `published_from` / `published_to` を指定すると、この
         *     ハード除外の内側でしか絞り込みが効かず黙って 0 件になっていた
         *     （Issue #90 自己レビューで判明した不具合そのもの）。
         *
         *     ページングは番号付き（`page` / `limit`）で、run 内の rank に対する offset
         *     として扱う。`total_count` は run に保存された件数（Bad 除外前）であり、
         *     範囲外の `page` はエラーにせず空の `items` を返す。
         *
         *     古い run は `jobs/handlers/purge_recommendation_runs.py` が保持期間超過分を
         *     削除し、呼び出し過多は `rate_limit.py` のレート制限（Issue #28）が抑える。
         */
        get: operations["get_feed_api_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description アプリケーションの稼働状態を返す。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interest Topics
         * @description トピック単位の関心一覧を返す（`PROJECT_SPEC.md` §7.1, §7.2）。
         *
         *     `effective_weight` 降順（同値は `topic` 昇順）で返す。並び順を安定させる
         *     ためにタイブレークを必ず付ける（`recommendation/service.py` の他の並び順と
         *     同じ方針）。件数はトピックの語彙数に比例し高々数百件程度に収まる見込み
         *     のため、`cursor` ではなく単純な `offset`/`limit` にする（`api/articles.py`
         *     の関心記事一覧のような無限スクロール想定の cursor ページングは過剰）。
         */
        get: operations["list_interest_topics_api_interests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interest Clusters
         * @description 関心クラスタ一覧を返す（`PROJECT_SPEC.md` §8）。
         *
         *     `weight` 降順（同値は `label` 昇順）で返す。クラスタ数は
         *     `config/scoring.yaml` の `clustering.max_clusters` で上限が付いており
         *     （既定 8）小規模なため、ページングは設けない。
         */
        get: operations["list_interest_clusters_api_interests_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interest Summary
         * @description 関心分析画面向けのサマリーを返す（`PROJECT_SPEC.md` §7, §8, Issue #16）。
         *
         *     集計元は `article_feedback JOIN articles`（`user_articles` は使わない）。
         *     Good/Bad 比率は action 別の件数をそのまま返すが、内容分布系（技術・一次
         *     情報比率・content_type・難易度）は `af.action IN ('good', 'save')` に
         *     絞って集計する（Bad を付けた記事の属性まで「関心」として数えると実態と
         *     ずれるため）。ジャンル別関心度だけは例外で、good/save の positive_count に
         *     加えて bad の negative_count も返す（`InterestGenreItem` docstring 参照）。
         *
         *     抑制中のトピックは `user_topic_preferences.negative_weight > 0` の行を返す。
         *     抑制ロジック（`interest/topics.py`）が domain ではなく topic 粒度で動くため、
         *     ここも topic 粒度で返す（`GET /api/interests` と同じ ORM クエリ）。
         *
         *     集計は SQL 側で完結させ、Python へ全件ロードしない（`/timeline` と同じ方針）。
         *     データが 1 件も無いときは各リストが空配列、`feedback_ratio` /
         *     `primary_source_ratio` は全項目 0 になる（GROUP BY 無しの集約クエリは
         *     行が無くても必ず 1 行返るため、例外にはならない）。
         */
        get: operations["get_interest_summary_api_interests_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interest Timeline
         * @description 関心の推移を週単位のバケットへ集計して返す。
         *
         *     履歴テーブルは新設せず、`user_articles.created_at` と
         *     `article_feedback.created_at` を集計元にする。`weeks` は `now` から
         *     `weeks * 7日` 遡った時刻以降を対象にする目安であり、境界週は部分週に
         *     なりうる（ちょうど週の途中から `since` が始まるため）。
         *
         *     データが1件も無い週はバケットを作らない（0 件のバケットを並べても
         *     情報量が無いため）。トピック別集計とは独立に、関心記事の追加件数
         *     （`user_articles`）も同じ週バケットへ載せて返す。
         */
        get: operations["get_interest_timeline_api_interests_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description ジョブの進捗を取得する。
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description 登録済みの情報源を一覧する。
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        /**
         * Create Source
         * @description 情報源を登録する。
         */
        post: operations["create_source_api_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Source
         * @description 情報源を部分更新する。
         *
         *     更新した行は手動確認済みとして扱う（`verified` を明示指定した場合はそれに従う）。
         */
        patch: operations["update_source_api_sources__source_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArticleFeedbackCreate
         * @description フィードバック登録リクエスト。
         */
        ArticleFeedbackCreate: {
            action: components["schemas"]["FeedbackAction"];
            reason?: components["schemas"]["BadReason"] | null;
        };
        /**
         * ArticleFeedbackResponse
         * @description フィードバックの公開表現。
         *
         *     `action` / `reason` は enum 型にする。`str` のままだと OpenAPI に enum が出ず、
         *     生成される `frontend/src/lib/api-schema.d.ts` でも単なる `string` になり、
         *     フロント側の文字列リテラル比較が型で守られない（Issue #13 自己レビュー B）。
         *     DB の `action` / `reason` 列は text 型だが、`from_attributes=True` により
         *     pydantic がその文字列値から enum メンバーへ変換する。
         */
        ArticleFeedbackResponse: {
            action: components["schemas"]["FeedbackAction"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            reason: components["schemas"]["BadReason"] | null;
        };
        /**
         * ArticleOrigin
         * @description 関心記事に追加された経路（`PROJECT_SPEC.md` §7.1 の重み表に対応）。
         * @enum {string}
         */
        ArticleOrigin: "manual" | "good" | "saved" | "read_full" | "clicked";
        /**
         * ArticleRecommendationsResponse
         * @description 記事起点推薦（`POST /api/articles/{article_id}/recommendations`）のレスポンス。
         */
        ArticleRecommendationsResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Mode */
            mode: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * ArticleRegistrationCreate
         * @description URL 登録リクエスト。
         *
         *     SSRF 対策そのもの（内部アドレスの拒否等）は実際に取得する
         *     `techradar.fetcher` 側の責務のため、ここではスキームと長さの形式検証に
         *     留める（`crawl.py` の `CrawlRunCreate` と同じ方針）。
         */
        ArticleRegistrationCreate: {
            /** Url */
            url: string;
        };
        /**
         * ArticleRegistrationResponse
         * @description 登録の公開表現。
         *
         *     `normalized_url` と `user_id` は含めない。内部の正規化結果やユーザー識別子を
         *     無用に露出させないため（`jobs.py` の `JobResponse` と同じ方針）。
         */
        ArticleRegistrationResponse: {
            /** Article Id */
            article_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Reason */
            error_reason: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /**
         * BadReason
         * @description Bad の理由（`PROJECT_SPEC.md` §7.2）。任意項目。
         * @enum {string}
         */
        BadReason: "not_interested" | "too_shallow" | "already_known" | "promotional" | "untrusted_source" | "too_repetitive";
        /** Body_bulk_import_article_registrations_api_articles_bulk_post */
        Body_bulk_import_article_registrations_api_articles_bulk_post: {
            /**
             * File
             * @description URLリストファイル（.md / .txt、UTF-8）
             */
            file: string;
        };
        /**
         * BulkArticleImportResponse
         * @description URL リストファイルの一括登録結果（`POST /api/articles/bulk`）。
         */
        BulkArticleImportResponse: {
            /** Created */
            created: components["schemas"]["ArticleRegistrationResponse"][];
            /** Created Count */
            created_count: number;
            /** Duplicate Count */
            duplicate_count: number;
            /** Error Count */
            error_count: number;
            /** Errors */
            errors: components["schemas"]["BulkImportErrorItem"][];
        };
        /**
         * BulkImportErrorItem
         * @description 一括登録でエラーとして扱った行の情報。
         */
        BulkImportErrorItem: {
            /** Line */
            line: string;
            /** Line Number */
            line_number: number;
            /** Reason */
            reason: string;
        };
        /**
         * CrawlRunCreate
         * @description 巡回ジョブの起動リクエスト。省略可能。
         */
        CrawlRunCreate: {
            /** Source Domain */
            source_domain?: string | null;
        };
        /**
         * CrawlRunResponse
         * @description 巡回ジョブの起動結果。
         */
        CrawlRunResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: string;
        };
        /**
         * FeedResponse
         * @description Discover フィード（`GET /api/feed`）のレスポンス（Issue #90）。
         *
         *     ページングは番号付きページ（`page` / `page_size`）に統一する。
         *     `total_count` は絞り込み後に run へ保存された件数（`count_recommendations`）で、
         *     `limits.feed_run_size`（`config/scoring.yaml`）を超える候補は元々対象外になる
         *     （決定済みの設計）。
         */
        FeedResponse: {
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Count */
            total_count: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * FeedbackAction
         * @description 記事へのフィードバック種別。
         * @enum {string}
         */
        FeedbackAction: "good" | "bad" | "save";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ヘルスチェックのレスポンス。
         */
        HealthResponse: {
            /** Brave Search Enabled */
            brave_search_enabled: boolean;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * InterestArticleItem
         * @description 関心記事一覧（`GET /api/articles`）1 件のレスポンス（`PROJECT_SPEC.md` §6.3）。
         */
        InterestArticleItem: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Canonical Url */
            canonical_url: string;
            /** Category */
            category: string | null;
            /** Content Type */
            content_type: string | null;
            /** Domain */
            domain: string | null;
            /** Is Primary Source */
            is_primary_source: boolean;
            /** Language */
            language: string | null;
            origin: components["schemas"]["ArticleOrigin"];
            /** Original Url */
            original_url: string;
            /** Published At */
            published_at: string | null;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /** Source Domain */
            source_domain: string;
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
            /** Translated Title */
            translated_title: string | null;
        };
        /**
         * InterestArticleListResponse
         * @description 関心記事一覧のレスポンス（ページングは Issue #91 で番号付きへ変更）。
         *
         *     `GET /api/feed` の `FeedResponse` と同じ形にそろえ、画面側の
         *     `components/ui/Pagination` を両方から同じように使えるようにする。
         */
        InterestArticleListResponse: {
            /** Items */
            items: components["schemas"]["InterestArticleItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Count */
            total_count: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * InterestClusterItem
         * @description 関心クラスタ 1 件のレスポンス。
         *
         *     `centroid_embedding` は 1024 次元でレスポンスが肥大化するため返さない
         *     （閲覧用途では不要な内部表現のため）。
         */
        InterestClusterItem: {
            /** Label */
            label: string;
            /** Topics */
            topics: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weight */
            weight: number;
        };
        /**
         * InterestClusterListResponse
         * @description `GET /api/interests/clusters` のレスポンス。
         */
        InterestClusterListResponse: {
            /** Items */
            items: components["schemas"]["InterestClusterItem"][];
        };
        /**
         * InterestContentTypeItem
         * @description 記事の性質（`articles.content_type`）別の件数 1 件。
         */
        InterestContentTypeItem: {
            /** Content Type */
            content_type: string | null;
            /** Count */
            count: number;
        };
        /**
         * InterestDifficultyItem
         * @description 難易度（`articles.difficulty`）別の件数 1 件。
         */
        InterestDifficultyItem: {
            /** Count */
            count: number;
            /** Difficulty */
            difficulty: string | null;
        };
        /**
         * InterestFeedbackRatio
         * @description action 別のフィードバック件数（`GET /api/interests/summary` 用）。
         */
        InterestFeedbackRatio: {
            /** Bad Count */
            bad_count: number;
            /** Good Count */
            good_count: number;
            /** Save Count */
            save_count: number;
        };
        /**
         * InterestGenreItem
         * @description ジャンル（`articles.domain`）単位の関心度 1 件。
         *
         *     他の内容分布系（technologies / content_types / difficulties）と異なり
         *     good/save に絞らず、`negative_count`（Bad の件数）も併せて返す。「抑制中の
         *     ジャンル」（`suppressed_topics`、topic 粒度）とは別軸で、domain 粒度でも
         *     Good/Bad の傾向を見たいという要求に応えるため（Issue #16）。
         */
        InterestGenreItem: {
            /** Domain */
            domain: string | null;
            /** Negative Count */
            negative_count: number;
            /** Positive Count */
            positive_count: number;
        };
        /**
         * InterestPrimarySourceRatio
         * @description 一次情報比率（`articles.is_primary_source`）。
         */
        InterestPrimarySourceRatio: {
            /** Primary Count */
            primary_count: number;
            /** Secondary Count */
            secondary_count: number;
        };
        /**
         * InterestSummaryResponse
         * @description `GET /api/interests/summary` のレスポンス（関心分析画面向け、Issue #16）。
         */
        InterestSummaryResponse: {
            /** Content Types */
            content_types: components["schemas"]["InterestContentTypeItem"][];
            /** Difficulties */
            difficulties: components["schemas"]["InterestDifficultyItem"][];
            feedback_ratio: components["schemas"]["InterestFeedbackRatio"];
            /** Genres */
            genres: components["schemas"]["InterestGenreItem"][];
            primary_source_ratio: components["schemas"]["InterestPrimarySourceRatio"];
            /** Suppressed Topics */
            suppressed_topics: components["schemas"]["SuppressedTopicItem"][];
            /** Technologies */
            technologies: components["schemas"]["InterestTechnologyItem"][];
        };
        /**
         * InterestTechnologyItem
         * @description 技術タグ（`articles.technologies`）単位の関心記事件数 1 件。
         */
        InterestTechnologyItem: {
            /** Count */
            count: number;
            /** Technology */
            technology: string;
        };
        /**
         * InterestTimelineBucket
         * @description タイムラインの 1 週バケット。
         */
        InterestTimelineBucket: {
            /** Interest Article Count */
            interest_article_count: number;
            /** Topics */
            topics: components["schemas"]["InterestTimelineTopicStats"][];
            /**
             * Week Start
             * Format: date-time
             */
            week_start: string;
        };
        /**
         * InterestTimelineResponse
         * @description `GET /api/interests/timeline` のレスポンス。
         */
        InterestTimelineResponse: {
            /** Buckets */
            buckets: components["schemas"]["InterestTimelineBucket"][];
        };
        /**
         * InterestTimelineTopicStats
         * @description タイムラインの 1 週バケット内、1 トピックぶんの集計。
         */
        InterestTimelineTopicStats: {
            /** Negative Count */
            negative_count: number;
            /** Positive Count */
            positive_count: number;
            /** Topic */
            topic: string;
        };
        /**
         * InterestTopicItem
         * @description トピック単位の関心 1 件（`user_topic_preferences` 1 行）のレスポンス。
         */
        InterestTopicItem: {
            /** Effective Weight */
            effective_weight: number;
            /** Negative Weight */
            negative_weight: number;
            /** Positive Weight */
            positive_weight: number;
            /** Topic */
            topic: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InterestTopicListResponse
         * @description `GET /api/interests` のレスポンス。
         */
        InterestTopicListResponse: {
            /** Items */
            items: components["schemas"]["InterestTopicItem"][];
        };
        /**
         * JobResponse
         * @description ジョブ 1 件の進捗レスポンス。
         *
         *     `payload` は含めない。ジョブの投入内容には将来 URL など内部情報が
         *     入りうるため、進捗確認 API で無条件に露出させない。
         *
         *     `last_error` も同様の理由で含めない。失敗理由は例外メッセージそのものであり、
         *     今後 fetch_article などが外部 HTTP を叩くハンドラを持つと、アクセス先 URL や
         *     クエリパラメータ（API キーを含みうる）がそのまま入りうる。この進捗確認 API は
         *     無認証で叩けるため、ここで露出させると内部情報の漏洩経路になる。失敗理由は
         *     `operation_logs.error_reason`（非公開経路）に別途記録される。
         */
        JobResponse: {
            /** Attempts */
            attempts: number;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /**
         * RateLimitedResponse
         * @description 429 のレスポンスボディ（`HTTPException` の既定形）。
         */
        RateLimitedResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * RecommendationItem
         * @description 推薦結果 1 件のレスポンス。
         *
         *     記事本文（`Article.body`）は含めない（ADR 0001、外部には表示しない）。
         */
        RecommendationItem: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Canonical Url */
            canonical_url: string;
            feedback: components["schemas"]["ArticleFeedbackResponse"] | null;
            /** Is Primary Source */
            is_primary_source: boolean;
            /** Is Read */
            is_read: boolean;
            /** Language */
            language: string | null;
            /** Original Url */
            original_url: string;
            /** Published At */
            published_at: string | null;
            /** Rank */
            rank: number;
            /** Reasons */
            reasons: {
                [key: string]: number | string;
            };
            /** Score */
            score: number;
            /** Source Domain */
            source_domain: string;
            /** Summary Ja */
            summary_ja: string | null;
            /** Technologies */
            technologies: string[];
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
            /** Translated Title */
            translated_title: string | null;
        };
        /**
         * SourceCreate
         * @description レジストリの新規登録。
         */
        SourceCreate: {
            /** Authority Score */
            authority_score: number;
            /** Domain */
            domain: string;
            /** Entity Name */
            entity_name: string;
            /** Github Org */
            github_org?: string | null;
            /** Path Pattern */
            path_pattern?: string | null;
            source_type: components["schemas"]["SourceType"];
            /**
             * Verified
             * @default true
             */
            verified: boolean;
        };
        /**
         * SourceResponse
         * @description レジストリ 1 件のレスポンス。
         */
        SourceResponse: {
            /** Authority Score */
            authority_score: number;
            /** Domain */
            domain: string;
            /** Entity Name */
            entity_name: string;
            /** Github Org */
            github_org: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Path Pattern */
            path_pattern: string | null;
            /** Source Type */
            source_type: string;
            /** Verified */
            verified: boolean;
        };
        /**
         * SourceType
         * @description 情報源の種別（`PROJECT_SPEC.md` §10 の Tier 分類に対応）。
         * @enum {string}
         */
        SourceType: "official_documentation" | "api_specification" | "standard_specification" | "official_release_notes" | "official_blog" | "official_research" | "original_paper" | "official_github_release" | "company_tech_blog" | "maintainer_article" | "personal_article" | "tech_media" | "news_repost" | "summary_repost" | "unknown";
        /**
         * SourceUpdate
         * @description レジストリの部分更新。
         *
         *     省略した項目は変更しない。`domain`・`path_pattern`・`github_org` は一意制約
         *     `uq_source_registry_domain` を構成するキーであり、`service._rule_key` の
         *     同一性判定にも使われるため変更させない（別のパターンにしたい場合は新規登録
         *     する）。ここを変更可能にすると、PATCH で行のキーを変えた後にシーダーを
         *     走らせたとき、変更前のキーに一致する config 側の原ルールが「存在しない」と
         *     判定されて別行として再投入され、手直しした行と矛盾する形で併存してしまう。
         */
        SourceUpdate: {
            /** Authority Score */
            authority_score?: number | null;
            /** Entity Name */
            entity_name?: string | null;
            source_type?: components["schemas"]["SourceType"] | null;
            /** Verified */
            verified?: boolean | null;
        };
        /**
         * SuppressedTopicItem
         * @description 抑制中のトピック 1 件（`user_topic_preferences.negative_weight > 0`）。
         *
         *     抑制ロジック（`interest/topics.py` の `compute_negative_weight`）は
         *     domain ではなく topic 粒度で動くため、ここも topic 粒度で返す。
         */
        SuppressedTopicItem: {
            /** Effective Weight */
            effective_weight: number;
            /** Negative Weight */
            negative_weight: number;
            /** Topic */
            topic: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_interest_articles_api_articles_get: {
        parameters: {
            query?: {
                /** @description 登録方法。複数指定可 */
                origin?: components["schemas"]["ArticleOrigin"][] | null;
                /** @description 検索語。title/translated_title/summary_jaへの部分一致（大文字小文字を区別しない） */
                q?: string | null;
                /** @description トピック。複数指定時は指定した全てを含む記事に絞る（AND） */
                topics?: string[] | null;
                /** @description 技術タグ。複数指定時は指定した全てを含む記事に絞る（AND） */
                technologies?: string[] | null;
                /** @description ジャンル大分類 */
                domain?: string | null;
                /** @description ジャンル中分類 */
                category?: string | null;
                /** @description 情報源 */
                source_domain?: string | null;
                /** @description 言語 */
                language?: string | null;
                /** @description 登録日時の期間（下限、含む） */
                registered_from?: string | null;
                /** @description 登録日時の期間（上限、含む） */
                registered_to?: string | null;
                /** @description 公式 / 非公式 */
                is_primary_source?: boolean | null;
                /** @description 1始まりのページ番号 */
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestArticleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_registration_api_articles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleRegistrationCreate"];
            };
        };
        responses: {
            /** @description 同一 URL の登録が既に存在するため、新規作成せず既存の登録を返した。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_import_article_registrations_api_articles_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_bulk_import_article_registrations_api_articles_bulk_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkArticleImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_registration_api_articles_registrations__registration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_feedback_api_articles__article_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleFeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_article_feedback_api_articles__article_id__feedback_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interest_article_api_articles__article_id__interest_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_recommendations_api_articles__article_id__recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 単位時間あたりのリクエスト数が上限を超えた。`Retry-After` ヘッダに再試行までの待機秒数が入る。 */
            429: {
                headers: {
                    /** @description 再試行までの待機秒数（整数へ切り上げ）。 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedResponse"];
                };
            };
        };
    };
    create_crawl_run_api_crawl_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CrawlRunCreate"] | null;
            };
        };
        responses: {
            /** @description pending または実行中の crawl_sources ジョブが既に存在するため、新規作成せず既存ジョブを返した。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_api_feed_get: {
        parameters: {
            query?: {
                /** @description 検索語。title/translated_title/summary_jaへの部分一致（大文字小文字を区別しない） */
                q?: string | null;
                /** @description トピック。複数指定時は指定した全てを含む記事に絞る（AND） */
                topics?: string[] | null;
                /** @description 技術タグ。複数指定時は指定した全てを含む記事に絞る（AND） */
                technologies?: string[] | null;
                /** @description 公開日の下限（published_at、NULLはfetched_atで代替） */
                published_from?: string | null;
                /** @description 公開日の上限 */
                published_to?: string | null;
                /** @description 情報源ドメインの完全一致 */
                source_domain?: string | null;
                /** @description フィード対象期間（日数）。省略時はconfig/scoring.yamlのfreshness.max_age_daysを使う。freshnessスコアの減衰基準（新しさの点数）はこの値を変えても変わらない */
                max_age_days?: number;
                /** @description 1始まりのページ番号 */
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 単位時間あたりのリクエスト数が上限を超えた。`Retry-After` ヘッダに再試行までの待機秒数が入る。 */
            429: {
                headers: {
                    /** @description 再試行までの待機秒数（整数へ切り上げ）。 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_interest_topics_api_interests_get: {
        parameters: {
            query?: {
                /** @description 取得件数 */
                limit?: number;
                /** @description スキップする件数 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestTopicListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interest_clusters_api_interests_clusters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestClusterListResponse"];
                };
            };
        };
    };
    get_interest_summary_api_interests_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestSummaryResponse"];
                };
            };
        };
    };
    get_interest_timeline_api_interests_timeline_get: {
        parameters: {
            query?: {
                /** @description 遡って集計する週数 */
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: {
                /** @description ドメインの部分一致で絞り込む */
                domain?: string | null;
                /** @description 企業・OSS 名の部分一致で絞り込む */
                entity_name?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_api_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
