/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interest Articles
         * @description 関心記事一覧を返す（`PROJECT_SPEC.md` §6.3）。
         *
         *     手動登録・Good・保存の3経路のみを対象にし、登録日時（`user_articles.created_at`）
         *     降順で返す。タイブレークに `user_articles.id` を使い、cursor はこの2つの組から作る。
         */
        get: operations["list_interest_articles_api_articles_get"];
        put?: never;
        /**
         * Create Article Registration
         * @description URL を登録し、記事取得ジョブを積む。
         *
         *     同じ URL（正規化後）を何度も登録しても fetch ジョブを積み増さないよう、
         *     既存登録があればそれをそのまま返す。
         */
        post: operations["create_article_registration_api_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/registrations/{registration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article Registration
         * @description 登録の状態を取得する。
         *
         *     作成側と同じく `user_id` で絞る。絞らないままにすると、認証を導入した際に
         *     このエンドポイントだけ他ユーザーの登録を返してしまう。
         */
        get: operations["get_article_registration_api_articles_registrations__registration_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{article_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Article Feedback
         * @description 記事へ Good / Bad / 保存を記録する（`PROJECT_SPEC.md` §7）。
         *
         *     合わせてトピック単位の選好（`user_topic_preferences`）を同期更新し
         *     （`update_topic_preferences`）、関心クラスタの再構築ジョブを積む
         *     （`_enqueue_interest_cluster_rebuild`、Issue #15）。
         */
        post: operations["create_article_feedback_api_articles__article_id__feedback_post"];
        /**
         * Delete Article Feedback
         * @description 記事へのフィードバックを取り消す。
         *
         *     Good / 保存に由来する `user_articles` 行も合わせて削除する
         *     （手動登録由来の行は残す）。関心記事の構成が変わりうるため、関心クラスタの
         *     再構築ジョブも積む。
         *
         *     トピック単位の選好（`user_topic_preferences`）は更新しない。
         *     `interest/topics.py` の関数はいずれも増加方向のみで、取り消し時に
         *     「その分を差し引く」ための減少関数を持たない（`update_topic_preferences`
         *     の docstring 参照）。取り消し時に同じ関数を呼ぶと、削除したはずの
         *     フィードバックの効果を新たに加算してしまい、意味が逆転するため呼ばない。
         */
        delete: operations["delete_article_feedback_api_articles__article_id__feedback_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{article_id}/interest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Interest Article
         * @description 記事を関心記事一覧から除外する。
         *
         *     `user_articles` の該当行を削除するだけで、`article_feedback` には触れない
         *     （Bad フィードバックも付けない）。「興味がない」（Bad）と「間違って登録した」
         *     （一覧からの除外）は別の意思表示のため区別する（Issue #14 ヒアリング済み決定事項）。
         */
        delete: operations["delete_interest_article_api_articles__article_id__interest_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{article_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Article Recommendations
         * @description 指定記事に近い記事を推薦する（`PROJECT_SPEC.md` §13.1）。
         *
         *     構成比は適用せず、`rank_candidates` の上位をそのまま rank 昇順で返す
         *     （`recommendation/service.py` の ARTICLE_BASED モード）。
         */
        post: operations["create_article_recommendations_api_articles__article_id__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Crawl Run
         * @description 巡回ジョブを enqueue する。
         *
         *     UI のボタン連打などで重複起動されると、`crawl_sources` 1件ごとに発生する
         *     検索 API / LLM 呼び出しが無制限に積み上がり、追加課金ゼロという前提に
         *     直接影響する。pending または実行中 status の `crawl_sources` ジョブが既に
         *     存在する場合は新規作成せず、その job_id を 200 OK で返す。存在しなければ
         *     従来どおり新規に enqueue して 201 Created を返す。
         *
         *     事前確認と INSERT の間には別リクエストが割り込みうる（TOCTOU）。SELECT 時点で
         *     対象の行が無い以上、行ロックでは塞げないため、最終的な排他は部分ユニーク
         *     インデックス `ux_jobs_active_crawl_sources` に任せ、ここではその違反を
         *     「相手が先に積んだ」ものとして扱う。
         */
        post: operations["create_crawl_run_api_crawl_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feed
         * @description Discover フィードを返す（`PROJECT_SPEC.md` §13.2）。
         *
         *     `cursor` 省略時は、直近の run が再利用してよい時間内（`config/scoring.yaml` の
         *     `limits.feed_run_reuse_seconds`）ならその run の先頭ページを返し、そうでなければ
         *     新しい run を生成して DISCOVER モードの先頭ページを返す（`_resolve_discover_run_id`）。
         *     `cursor` 指定時は cursor が指すのと同じ run を rank 順に辿ることで、
         *     ページ間で重複が出ないようにする（受入基準）。
         *
         *     `next_cursor` は Bad 除外（`_build_items`）より前の行から計算する。除外の有無で
         *     cursor が巻き戻らないようにするためで、その結果 `items` が空でも `next_cursor` が
         *     非 null になりうる（ページ内が全件 Bad の場合）。呼び出し側は `items` の空だけで
         *     終端と判断せず、`next_cursor` が null になるまで辿ること。
         *
         *     古い run は `jobs/handlers/purge_recommendation_runs.py` が保持期間超過分を
         *     削除し、呼び出し過多は `rate_limit.py` のレート制限（Issue #28）が抑える。
         */
        get: operations["get_feed_api_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description アプリケーションの稼働状態を返す。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interest Topics
         * @description トピック単位の関心一覧を返す（`PROJECT_SPEC.md` §7.1, §7.2）。
         *
         *     `effective_weight` 降順（同値は `topic` 昇順）で返す。並び順を安定させる
         *     ためにタイブレークを必ず付ける（`recommendation/service.py` の他の並び順と
         *     同じ方針）。件数はトピックの語彙数に比例し高々数百件程度に収まる見込み
         *     のため、`cursor` ではなく単純な `offset`/`limit` にする（`api/articles.py`
         *     の関心記事一覧のような無限スクロール想定の cursor ページングは過剰）。
         */
        get: operations["list_interest_topics_api_interests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interest Clusters
         * @description 関心クラスタ一覧を返す（`PROJECT_SPEC.md` §8）。
         *
         *     `weight` 降順（同値は `label` 昇順）で返す。クラスタ数は
         *     `config/scoring.yaml` の `clustering.max_clusters` で上限が付いており
         *     （既定 8）小規模なため、ページングは設けない。
         */
        get: operations["list_interest_clusters_api_interests_clusters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interest Timeline
         * @description 関心の推移を週単位のバケットへ集計して返す。
         *
         *     履歴テーブルは新設せず、`user_articles.created_at` と
         *     `article_feedback.created_at` を集計元にする。`weeks` は `now` から
         *     `weeks * 7日` 遡った時刻以降を対象にする目安であり、境界週は部分週に
         *     なりうる（ちょうど週の途中から `since` が始まるため）。
         *
         *     データが1件も無い週はバケットを作らない（0 件のバケットを並べても
         *     情報量が無いため）。トピック別集計とは独立に、関心記事の追加件数
         *     （`user_articles`）も同じ週バケットへ載せて返す。
         */
        get: operations["get_interest_timeline_api_interests_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description ジョブの進捗を取得する。
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description 登録済みの情報源を一覧する。
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        /**
         * Create Source
         * @description 情報源を登録する。
         */
        post: operations["create_source_api_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Source
         * @description 情報源を部分更新する。
         *
         *     更新した行は手動確認済みとして扱う（`verified` を明示指定した場合はそれに従う）。
         */
        patch: operations["update_source_api_sources__source_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArticleFeedbackCreate
         * @description フィードバック登録リクエスト。
         */
        ArticleFeedbackCreate: {
            action: components["schemas"]["FeedbackAction"];
            reason?: components["schemas"]["BadReason"] | null;
        };
        /**
         * ArticleFeedbackResponse
         * @description フィードバックの公開表現。
         *
         *     `action` / `reason` は enum 型にする。`str` のままだと OpenAPI に enum が出ず、
         *     生成される `frontend/src/lib/api-schema.d.ts` でも単なる `string` になり、
         *     フロント側の文字列リテラル比較が型で守られない（Issue #13 自己レビュー B）。
         *     DB の `action` / `reason` 列は text 型だが、`from_attributes=True` により
         *     pydantic がその文字列値から enum メンバーへ変換する。
         */
        ArticleFeedbackResponse: {
            action: components["schemas"]["FeedbackAction"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            reason: components["schemas"]["BadReason"] | null;
        };
        /**
         * ArticleOrigin
         * @description 関心記事に追加された経路（`PROJECT_SPEC.md` §7.1 の重み表に対応）。
         * @enum {string}
         */
        ArticleOrigin: "manual" | "good" | "saved" | "read_full" | "clicked";
        /**
         * ArticleRecommendationsResponse
         * @description 記事起点推薦（`POST /api/articles/{article_id}/recommendations`）のレスポンス。
         */
        ArticleRecommendationsResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Mode */
            mode: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * ArticleRegistrationCreate
         * @description URL 登録リクエスト。
         *
         *     SSRF 対策そのもの（内部アドレスの拒否等）は実際に取得する
         *     `techradar.fetcher` 側の責務のため、ここではスキームと長さの形式検証に
         *     留める（`crawl.py` の `CrawlRunCreate` と同じ方針）。
         */
        ArticleRegistrationCreate: {
            /** Url */
            url: string;
        };
        /**
         * ArticleRegistrationResponse
         * @description 登録の公開表現。
         *
         *     `normalized_url` と `user_id` は含めない。内部の正規化結果やユーザー識別子を
         *     無用に露出させないため（`jobs.py` の `JobResponse` と同じ方針）。
         */
        ArticleRegistrationResponse: {
            /** Article Id */
            article_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Reason */
            error_reason: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /**
         * BadReason
         * @description Bad の理由（`PROJECT_SPEC.md` §7.2）。任意項目。
         * @enum {string}
         */
        BadReason: "not_interested" | "too_shallow" | "already_known" | "promotional" | "untrusted_source" | "too_repetitive";
        /**
         * CrawlRunCreate
         * @description 巡回ジョブの起動リクエスト。省略可能。
         */
        CrawlRunCreate: {
            /** Source Domain */
            source_domain?: string | null;
        };
        /**
         * CrawlRunResponse
         * @description 巡回ジョブの起動結果。
         */
        CrawlRunResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: string;
        };
        /**
         * FeedResponse
         * @description Discover フィード（`GET /api/feed`）のレスポンス。
         */
        FeedResponse: {
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * FeedbackAction
         * @description 記事へのフィードバック種別。
         * @enum {string}
         */
        FeedbackAction: "good" | "bad" | "save";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ヘルスチェックのレスポンス。
         */
        HealthResponse: {
            /** Brave Search Enabled */
            brave_search_enabled: boolean;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * InterestArticleItem
         * @description 関心記事一覧（`GET /api/articles`）1 件のレスポンス（`PROJECT_SPEC.md` §6.3）。
         */
        InterestArticleItem: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Canonical Url */
            canonical_url: string;
            /** Category */
            category: string | null;
            /** Content Type */
            content_type: string | null;
            /** Domain */
            domain: string | null;
            /** Is Primary Source */
            is_primary_source: boolean;
            /** Language */
            language: string | null;
            origin: components["schemas"]["ArticleOrigin"];
            /** Original Url */
            original_url: string;
            /** Published At */
            published_at: string | null;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /** Source Domain */
            source_domain: string;
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
            /** Translated Title */
            translated_title: string | null;
        };
        /**
         * InterestArticleListResponse
         * @description 関心記事一覧のレスポンス。
         */
        InterestArticleListResponse: {
            /** Items */
            items: components["schemas"]["InterestArticleItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * InterestClusterItem
         * @description 関心クラスタ 1 件のレスポンス。
         *
         *     `centroid_embedding` は 1024 次元でレスポンスが肥大化するため返さない
         *     （閲覧用途では不要な内部表現のため）。
         */
        InterestClusterItem: {
            /** Label */
            label: string;
            /** Topics */
            topics: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weight */
            weight: number;
        };
        /**
         * InterestClusterListResponse
         * @description `GET /api/interests/clusters` のレスポンス。
         */
        InterestClusterListResponse: {
            /** Items */
            items: components["schemas"]["InterestClusterItem"][];
        };
        /**
         * InterestTimelineBucket
         * @description タイムラインの 1 週バケット。
         */
        InterestTimelineBucket: {
            /** Interest Article Count */
            interest_article_count: number;
            /** Topics */
            topics: components["schemas"]["InterestTimelineTopicStats"][];
            /**
             * Week Start
             * Format: date-time
             */
            week_start: string;
        };
        /**
         * InterestTimelineResponse
         * @description `GET /api/interests/timeline` のレスポンス。
         */
        InterestTimelineResponse: {
            /** Buckets */
            buckets: components["schemas"]["InterestTimelineBucket"][];
        };
        /**
         * InterestTimelineTopicStats
         * @description タイムラインの 1 週バケット内、1 トピックぶんの集計。
         */
        InterestTimelineTopicStats: {
            /** Negative Count */
            negative_count: number;
            /** Positive Count */
            positive_count: number;
            /** Topic */
            topic: string;
        };
        /**
         * InterestTopicItem
         * @description トピック単位の関心 1 件（`user_topic_preferences` 1 行）のレスポンス。
         */
        InterestTopicItem: {
            /** Effective Weight */
            effective_weight: number;
            /** Negative Weight */
            negative_weight: number;
            /** Positive Weight */
            positive_weight: number;
            /** Topic */
            topic: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InterestTopicListResponse
         * @description `GET /api/interests` のレスポンス。
         */
        InterestTopicListResponse: {
            /** Items */
            items: components["schemas"]["InterestTopicItem"][];
        };
        /**
         * JobResponse
         * @description ジョブ 1 件の進捗レスポンス。
         *
         *     `payload` は含めない。ジョブの投入内容には将来 URL など内部情報が
         *     入りうるため、進捗確認 API で無条件に露出させない。
         *
         *     `last_error` も同様の理由で含めない。失敗理由は例外メッセージそのものであり、
         *     今後 fetch_article などが外部 HTTP を叩くハンドラを持つと、アクセス先 URL や
         *     クエリパラメータ（API キーを含みうる）がそのまま入りうる。この進捗確認 API は
         *     無認証で叩けるため、ここで露出させると内部情報の漏洩経路になる。失敗理由は
         *     `operation_logs.error_reason`（非公開経路）に別途記録される。
         */
        JobResponse: {
            /** Attempts */
            attempts: number;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /**
         * RateLimitedResponse
         * @description 429 のレスポンスボディ（`HTTPException` の既定形）。
         */
        RateLimitedResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * RecommendationItem
         * @description 推薦結果 1 件のレスポンス。
         *
         *     記事本文（`Article.body`）は含めない（ADR 0001、外部には表示しない）。
         */
        RecommendationItem: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Canonical Url */
            canonical_url: string;
            feedback: components["schemas"]["ArticleFeedbackResponse"] | null;
            /** Is Primary Source */
            is_primary_source: boolean;
            /** Is Read */
            is_read: boolean;
            /** Language */
            language: string | null;
            /** Original Url */
            original_url: string;
            /** Published At */
            published_at: string | null;
            /** Rank */
            rank: number;
            /** Reasons */
            reasons: {
                [key: string]: number | string;
            };
            /** Score */
            score: number;
            /** Source Domain */
            source_domain: string;
            /** Summary Ja */
            summary_ja: string | null;
            /** Technologies */
            technologies: string[];
            /** Title */
            title: string;
            /** Topics */
            topics: string[];
            /** Translated Title */
            translated_title: string | null;
        };
        /**
         * SourceCreate
         * @description レジストリの新規登録。
         */
        SourceCreate: {
            /** Authority Score */
            authority_score: number;
            /** Domain */
            domain: string;
            /** Entity Name */
            entity_name: string;
            /** Github Org */
            github_org?: string | null;
            /** Path Pattern */
            path_pattern?: string | null;
            source_type: components["schemas"]["SourceType"];
            /**
             * Verified
             * @default true
             */
            verified: boolean;
        };
        /**
         * SourceResponse
         * @description レジストリ 1 件のレスポンス。
         */
        SourceResponse: {
            /** Authority Score */
            authority_score: number;
            /** Domain */
            domain: string;
            /** Entity Name */
            entity_name: string;
            /** Github Org */
            github_org: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Path Pattern */
            path_pattern: string | null;
            /** Source Type */
            source_type: string;
            /** Verified */
            verified: boolean;
        };
        /**
         * SourceType
         * @description 情報源の種別（`PROJECT_SPEC.md` §10 の Tier 分類に対応）。
         * @enum {string}
         */
        SourceType: "official_documentation" | "api_specification" | "standard_specification" | "official_release_notes" | "official_blog" | "official_research" | "original_paper" | "official_github_release" | "company_tech_blog" | "maintainer_article" | "personal_article" | "tech_media" | "news_repost" | "summary_repost" | "unknown";
        /**
         * SourceUpdate
         * @description レジストリの部分更新。
         *
         *     省略した項目は変更しない。`domain`・`path_pattern`・`github_org` は一意制約
         *     `uq_source_registry_domain` を構成するキーであり、`service._rule_key` の
         *     同一性判定にも使われるため変更させない（別のパターンにしたい場合は新規登録
         *     する）。ここを変更可能にすると、PATCH で行のキーを変えた後にシーダーを
         *     走らせたとき、変更前のキーに一致する config 側の原ルールが「存在しない」と
         *     判定されて別行として再投入され、手直しした行と矛盾する形で併存してしまう。
         */
        SourceUpdate: {
            /** Authority Score */
            authority_score?: number | null;
            /** Entity Name */
            entity_name?: string | null;
            source_type?: components["schemas"]["SourceType"] | null;
            /** Verified */
            verified?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_interest_articles_api_articles_get: {
        parameters: {
            query?: {
                /** @description 登録方法。複数指定可 */
                origin?: components["schemas"]["ArticleOrigin"][] | null;
                /** @description ジャンル大分類 */
                domain?: string | null;
                /** @description ジャンル中分類 */
                category?: string | null;
                /** @description 情報源 */
                source_domain?: string | null;
                /** @description 言語 */
                language?: string | null;
                /** @description 登録日時の期間（下限、含む） */
                registered_from?: string | null;
                /** @description 登録日時の期間（上限、含む） */
                registered_to?: string | null;
                /** @description 公式 / 非公式 */
                is_primary_source?: boolean | null;
                /** @description 前回レスポンスの next_cursor をそのまま渡す */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestArticleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_registration_api_articles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleRegistrationCreate"];
            };
        };
        responses: {
            /** @description 同一 URL の登録が既に存在するため、新規作成せず既存の登録を返した。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_registration_api_articles_registrations__registration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_feedback_api_articles__article_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleFeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_article_feedback_api_articles__article_id__feedback_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interest_article_api_articles__article_id__interest_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_recommendations_api_articles__article_id__recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 単位時間あたりのリクエスト数が上限を超えた。`Retry-After` ヘッダに再試行までの待機秒数が入る。 */
            429: {
                headers: {
                    /** @description 再試行までの待機秒数（整数へ切り上げ）。 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedResponse"];
                };
            };
        };
    };
    create_crawl_run_api_crawl_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CrawlRunCreate"] | null;
            };
        };
        responses: {
            /** @description pending または実行中の crawl_sources ジョブが既に存在するため、新規作成せず既存ジョブを返した。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_api_feed_get: {
        parameters: {
            query?: {
                /** @description 前回レスポンスの next_cursor をそのまま渡す */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 単位時間あたりのリクエスト数が上限を超えた。`Retry-After` ヘッダに再試行までの待機秒数が入る。 */
            429: {
                headers: {
                    /** @description 再試行までの待機秒数（整数へ切り上げ）。 */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_interest_topics_api_interests_get: {
        parameters: {
            query?: {
                /** @description 取得件数 */
                limit?: number;
                /** @description スキップする件数 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestTopicListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interest_clusters_api_interests_clusters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestClusterListResponse"];
                };
            };
        };
    };
    get_interest_timeline_api_interests_timeline_get: {
        parameters: {
            query?: {
                /** @description 遡って集計する週数 */
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterestTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: {
                /** @description ドメインの部分一致で絞り込む */
                domain?: string | null;
                /** @description 企業・OSS 名の部分一致で絞り込む */
                entity_name?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_api_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
