/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Article Registration
         * @description URL を登録し、記事取得ジョブを積む。
         *
         *     同じ URL（正規化後）を何度も登録しても fetch ジョブを積み増さないよう、
         *     既存登録があればそれをそのまま返す。
         */
        post: operations["create_article_registration_api_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/registrations/{registration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Article Registration
         * @description 登録の状態を取得する。
         */
        get: operations["get_article_registration_api_articles_registrations__registration_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Crawl Run
         * @description 巡回ジョブを enqueue する。
         *
         *     UI のボタン連打などで重複起動されると、`crawl_sources` 1件ごとに発生する
         *     検索 API / LLM 呼び出しが無制限に積み上がり、追加課金ゼロという前提に
         *     直接影響する。pending または実行中 status の `crawl_sources` ジョブが既に
         *     存在する場合は新規作成せず、その job_id を 200 OK で返す。存在しなければ
         *     従来どおり新規に enqueue して 201 Created を返す。
         */
        post: operations["create_crawl_run_api_crawl_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description アプリケーションの稼働状態を返す。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description ジョブの進捗を取得する。
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description 登録済みの情報源を一覧する。
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        /**
         * Create Source
         * @description 情報源を登録する。
         */
        post: operations["create_source_api_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Source
         * @description 情報源を部分更新する。
         *
         *     更新した行は手動確認済みとして扱う（`verified` を明示指定した場合はそれに従う）。
         */
        patch: operations["update_source_api_sources__source_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArticleRegistrationCreate
         * @description URL 登録リクエスト。
         *
         *     SSRF 対策そのもの（内部アドレスの拒否等）は実際に取得する
         *     `techradar.fetcher` 側の責務のため、ここではスキームと長さの形式検証に
         *     留める（`crawl.py` の `CrawlRunCreate` と同じ方針）。
         */
        ArticleRegistrationCreate: {
            /** Url */
            url: string;
        };
        /**
         * ArticleRegistrationResponse
         * @description 登録の公開表現。
         *
         *     `normalized_url` と `user_id` は含めない。内部の正規化結果やユーザー識別子を
         *     無用に露出させないため（`jobs.py` の `JobResponse` と同じ方針）。
         */
        ArticleRegistrationResponse: {
            /** Article Id */
            article_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Reason */
            error_reason: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /**
         * CrawlRunCreate
         * @description 巡回ジョブの起動リクエスト。省略可能。
         */
        CrawlRunCreate: {
            /** Source Domain */
            source_domain?: string | null;
        };
        /**
         * CrawlRunResponse
         * @description 巡回ジョブの起動結果。
         */
        CrawlRunResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ヘルスチェックのレスポンス。
         */
        HealthResponse: {
            /** Brave Search Enabled */
            brave_search_enabled: boolean;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * JobResponse
         * @description ジョブ 1 件の進捗レスポンス。
         *
         *     `payload` は含めない。ジョブの投入内容には将来 URL など内部情報が
         *     入りうるため、進捗確認 API で無条件に露出させない。
         *
         *     `last_error` も同様の理由で含めない。失敗理由は例外メッセージそのものであり、
         *     今後 fetch_article などが外部 HTTP を叩くハンドラを持つと、アクセス先 URL や
         *     クエリパラメータ（API キーを含みうる）がそのまま入りうる。この進捗確認 API は
         *     無認証で叩けるため、ここで露出させると内部情報の漏洩経路になる。失敗理由は
         *     `operation_logs.error_reason`（非公開経路）に別途記録される。
         */
        JobResponse: {
            /** Attempts */
            attempts: number;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /**
         * SourceCreate
         * @description レジストリの新規登録。
         */
        SourceCreate: {
            /** Authority Score */
            authority_score: number;
            /** Domain */
            domain: string;
            /** Entity Name */
            entity_name: string;
            /** Github Org */
            github_org?: string | null;
            /** Path Pattern */
            path_pattern?: string | null;
            source_type: components["schemas"]["SourceType"];
            /**
             * Verified
             * @default true
             */
            verified: boolean;
        };
        /**
         * SourceResponse
         * @description レジストリ 1 件のレスポンス。
         */
        SourceResponse: {
            /** Authority Score */
            authority_score: number;
            /** Domain */
            domain: string;
            /** Entity Name */
            entity_name: string;
            /** Github Org */
            github_org: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Path Pattern */
            path_pattern: string | null;
            /** Source Type */
            source_type: string;
            /** Verified */
            verified: boolean;
        };
        /**
         * SourceType
         * @description 情報源の種別（`PROJECT_SPEC.md` §10 の Tier 分類に対応）。
         * @enum {string}
         */
        SourceType: "official_documentation" | "api_specification" | "standard_specification" | "official_release_notes" | "official_blog" | "official_research" | "original_paper" | "official_github_release" | "company_tech_blog" | "maintainer_article" | "personal_article" | "tech_media" | "news_repost" | "summary_repost" | "unknown";
        /**
         * SourceUpdate
         * @description レジストリの部分更新。
         *
         *     省略した項目は変更しない。`domain`・`path_pattern`・`github_org` は一意制約
         *     `uq_source_registry_domain` を構成するキーであり、`service._rule_key` の
         *     同一性判定にも使われるため変更させない（別のパターンにしたい場合は新規登録
         *     する）。ここを変更可能にすると、PATCH で行のキーを変えた後にシーダーを
         *     走らせたとき、変更前のキーに一致する config 側の原ルールが「存在しない」と
         *     判定されて別行として再投入され、手直しした行と矛盾する形で併存してしまう。
         */
        SourceUpdate: {
            /** Authority Score */
            authority_score?: number | null;
            /** Entity Name */
            entity_name?: string | null;
            source_type?: components["schemas"]["SourceType"] | null;
            /** Verified */
            verified?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_article_registration_api_articles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleRegistrationCreate"];
            };
        };
        responses: {
            /** @description 同一 URL の登録が既に存在するため、新規作成せず既存の登録を返した。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_registration_api_articles_registrations__registration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crawl_run_api_crawl_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CrawlRunCreate"] | null;
            };
        };
        responses: {
            /** @description pending または実行中の crawl_sources ジョブが既に存在するため、新規作成せず既存ジョブを返した。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: {
                /** @description ドメインの部分一致で絞り込む */
                domain?: string | null;
                /** @description 企業・OSS 名の部分一致で絞り込む */
                entity_name?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_api_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
